name: Update LastUpdated.txt

on:
  push:
    branches: ['**']
    paths-ignore:
      - '/Assets/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stamp:
    # Prevent infinite loops on the bot's own commit
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Update timestamp
        shell: bash
        run: |
          set -euo pipefail
          FILE="/Assets/LastUpdated.txt"
          DATE_STR=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          echo "$DATE_STR" > "$FILE"
          if git diff --quiet -- "$FILE"; then
            echo "No changes to $FILE"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "chore: update LastUpdated.txt [skip ci]"
          git push
