name: Source index Maintainer (DO NOT TOUCH)

on:
  push:
    branches:
      - main  # Or replace with your branch
  workflow_dispatch:

permissions:
  contents: write  # 🔑 REQUIRED for committing back to the repo

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Directorys index
        shell: bash
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          DIR="Directorys"
          INDEX_FILE="$DIR/index.json"

          if [[ ! -d "$DIR" ]]; then
            echo "Directory '$DIR' does not exist; nothing to index."
            exit 0
          fi

          node -e "const fs=require('fs');const path=require('path');const dir='Directorys';const exclude=['index.json','index.html'];const items=fs.readdirSync(dir).filter(f=>!exclude.includes(f));const obj={Sources:[]};for(const it of items){obj[it]=\`./\${it}\`;}fs.writeFileSync(path.join(dir,'index.json'),JSON.stringify(obj,null,2));"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update Directorys/index.json'
          file_pattern: 'Directorys/index.json'
