name: Source index Maintainer (DO NOT TOUCH)

on:
  push:
    paths:
      - 'Directorys/Files/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Directorys/SourceList.json
        shell: bash
        run: |
          set -euo pipefail
          FILE_DIR="Directorys/Files"
          INDEX_FILE="Directorys/SourceList.json"

          if [[ ! -d "$FILE_DIR" ]]; then
            echo "Directory '$FILE_DIR' does not exist; nothing to index."
            exit 0
          fi

          node -e "
            const fs = require('fs');
            const path = require('path');
            const dir = '$FILE_DIR';
            const exclude = ['index.json', 'index.html'];
            const items = fs.readdirSync(dir).filter(f => !exclude.includes(f));
            const obj = { Sources: [] };
            for (const it of items) {
              obj[it] = '../Directorys/Files/' + it;
            }
            fs.writeFileSync('$INDEX_FILE', JSON.stringify(obj, null, 2));
          "

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update Directorys/SourceList.json'
          file_pattern: 'Directorys/SourceList.json'
